Import('env')

COMMON_OBJ = Glob('#/../bin/main/common/components/*.o') + Glob('#/../bin/main/common/util/*.o')
COMMON_OBJ += Glob('#/../bin/main/common/components/socket/*.o') + Glob('#/../bin/main/common/thread/*.o')
COMMON_OBJ += Glob('#/../bin/main/common/graph/*.o') + Glob('#/../bin/main/common/random/*.o')

DESER_OBJ = Glob('../../main/algos/simrank_odd_even/*.o')
DESER_OBJ += Glob('../../main/algos/simrank_update/*.o')
DESER_OBJ += Glob('../../main/algos/simrank_store_first/*.o')

env.Program('test_cluster_setup', ['test_cluster_setup.cpp', '../../main/algos/master.o', '../../main/algos/node.o', '../../main/algos/algo.o'] + COMMON_OBJ + DESER_OBJ)
