Import('env')

env.Object(Glob('*.cpp'))

COMMON_OBJ = Glob('#/../bin/main/common/components/socket/*.o')  + Glob('#/../bin/main/common/util/*.o') + Glob('#/../bin/main/common/random/*.o')
COMMON_OBJ += Glob('#/../bin/main/common/graph/*.o') + Glob('#/../bin/main/common/components/*.o') + ['#/../bin/main/algos/algo.o']
COMMON_OBJ += Glob('#/../bin/main/common/thread/*.o')
COMMON_OBJ += ['#/../bin/main/algos/node.o']

COMMON_OBJ += Glob('#/../bin/main/algos/simrank_odd_even/*.o')
COMMON_OBJ += Glob('#/../bin/main/algos/simrank_update/*.o')
COMMON_OBJ += Glob('#/../bin/main/algos/simrank_store_first/*.o')
COMMON_OBJ += Glob('#/../bin/main/algos/pagerank/*.o')
COMMON_OBJ += ['#/../bin/main/algos/psimrank/psimrank_deserializer.o', '#/../bin/main/algos/psimrank/psimrank_node.o']
COMMON_OBJ += ['#/../bin/main/algos/inner_master.o', '#/../bin/main/algos/master.o']
COMMON_OBJ += ['#/../bin/test/algos/simple_mock_algo/simple_mock_deserializer.o']
COMMON_OBJ += ['#/../bin/test/algos/simple_mock_algo/simple_mock_node.o']

env.Program('tournament_test', ['tournament_test.cpp', '../../../bin/main/common/util/tournament_maker.o'] )
env.Program('empty', ['empty.cpp'] )
env.Program('mycompare_test', ['mycompare_test.cpp'] )
env.Program('fp_reader_test', ['fp_reader_test.cpp'] + COMMON_OBJ)
env.Program('test_util', ['test_util.cpp'] + COMMON_OBJ)
env.Program('test_edgelist_container', ['test_edgelist_container.cpp'] + COMMON_OBJ)
env.Program('test_sender_buffer', ['test_sender_buffer.cpp'] + COMMON_OBJ )
env.Program('test_store_from_binary', ['test_store_from_binary.cpp'] + COMMON_OBJ)
env.Program('test_serializer', ['test_serializer.cpp'])
env.Program('test_fp_read', ['test_fp_read.cpp'] + COMMON_OBJ)
env.Program('test_random_generator', ['test_random_generator.cpp'] + COMMON_OBJ)
env.Program('test_hash_pseudo_random', ['test_hash_pseudo_random.cpp', '../../../bin/main/common/random/hash_pseudo_random.o'] )
