Import('env')


COMMON_OBJ = Glob('#/../bin/main/common/components/socket/*.o') + Glob('#/../bin/main/common/util/*.o')
COMMON_OBJ += Glob('#/../bin/main/common/thread/*.o') + Glob('#/../bin/main/common/components/*.o')
COMMON_OBJ += Glob('#/../bin/main/common/graph/*.o')  + Glob('#/../bin/main/common/random/*.o')
ALGO_OBJ = ['#/../bin/main/algos/algo.o', '#/../bin/main/algos/master.o', '#/../bin/main/algos/node.o', '#/../bin/main/algos/inner_master.o']

DESER_OBJ = Glob('#/../bin/main/algos/simrank_odd_even/*.o')
DESER_OBJ += Glob('#/../bin/main/algos/simrank_update/*.o')
DESER_OBJ += Glob('#/../bin/main/algos/simrank_store_first/*.o')
DESER_OBJ += Glob('#/../bin/main/algos/pagerank/*.o')
DESER_OBJ += ['#/../bin/main/algos/psimrank/psimrank_deserializer.o', '#/../bin/main/algos/psimrank/psimrank_node.o']
#DESER_OBJ += ['#/../bin/test/algos/simple_mock_algo/simple_mock_deserializer.o', '#/../bin/test/algos/simple_mock_algo/simple_mock_node.o']

COMP_OBJECTS = ['../../../main/algos/psimrank/psimrank_master.o']
COMMON_OBJ += ['#/../bin/main/algos/cluster.o', '#/../bin/main/algos/algo_builder.o', '#/../bin/main/algos/IMasterBuilder.o']
COMMON_OBJ += ['#/../bin/main/algos/test_simrank_odd_even_node_fatory.o', '#/../bin/main/algos/test_master_builder.o']
COMMON_OBJ += ['#/../bin/main/algos/node_factory_helper.o', '#/../bin/main/algos/inner_master_factory.o']
COMMON_OBJ += Glob('#/../bin/test/algos/simple_mock_algo/simple*.o')

env.Program('test_psimrank_master', ['test_psimrank_master.cpp'] + COMP_OBJECTS + COMMON_OBJ + DESER_OBJ + ALGO_OBJ)
env.Program('test_psimrank_algo', ['test_psimrank_algo.cpp'] + COMP_OBJECTS + COMMON_OBJ + DESER_OBJ + ALGO_OBJ)