Import('env', 'COMMON_OBJ', 'ALGO_OBJ')

env.Program('test_psimrank_master', ['test_psimrank_master.cpp'] + COMMON_OBJ + ALGO_OBJ)
env.Program('test_psimrank_algo', ['test_psimrank_algo.cpp'] + COMMON_OBJ + ALGO_OBJ)