Import('env')

env.Object(Glob('*.cpp'))

env.Program('filter_trusted_url', ['filter_trusted_url.cpp'] )
env.Program('tag_with_rownum', ['tag_with_rownum.cpp'] )
env.Program('dmoz_reader_job', ['dmoz_reader_job.cpp', 'dmoz_reader.o'] )
env.Program('distance_calculator', ['distance_calculator.cpp', 'dmoz_reader.o'] )
env.Program('distance_calculator_from_root', ['distance_calculator_from_root.cpp', 'dmoz_reader.o'] )
env.Program('ndcg_counter', ['ndcg_counter.cpp', 'ndcg.o'])
env.Program('get_simrank', ['get_simrank.cpp', 'simrank.o'])
