# -O3 jobban optimalizal
# -ggdb ezzel kell forditani, ha gdb-vel akarjuk debuggolni
# -pg gprof miatt?
# -g valgrind mint ?

# -O3 jobban optimalizal
# -ggdb ezzel kell forditani, ha gdb-vel akarjuk debuggolni
# -pg gprof miatt?
# -g valgrind mint ?

#flags = ['-O3', '-g', '-ggdb', '-Wall']
flags = [ '-g', '-ggdb', '-Wall']

GMOCK= "#../dep/gmock/"
LOG4CPP = "#../dep/log4cpp"
GMP = "#../dep/gmp/"
GTEST = "#../dep/gtest/"
ZMQ = '#../dep/zmq/'
GSL = '#../dep/gsl/'
env = Environment(
        CXX = 'g++',
        CCFLAGS = flags,
        CPPPATH=[ '#.', GMOCK + '/include/', LOG4CPP + '/include/', GMP + 'include/', GTEST + 'include/', ZMQ + 'include/', GSL + 'include/'],
        LIBPATH=['/usr/local/googlecode/lib', GMP + 'lib/', LOG4CPP + '/lib/', GMOCK + 'build/', GTEST + 'build/', ZMQ + 'lib/', GSL + 'lib/'],
        LIBS=['gtest', 'pthread', 'log4cpp', 'gmock', 'gmp', 'gmpxx', 'zmq', 'rt', 'gsl', 'gslcblas']
)

testCompile = ARGUMENTS.get('test', False)

SConscript([
    'main/common/SConscript'],
    exports = ['env'])
    
COMMON_OBJ = Glob('#/../bin/main/common/components/socket/*.o') + Glob('#/../bin/main/common/util/*.o')
COMMON_OBJ += Glob('#/../bin/main/common/thread/*.o') + Glob('#/../bin/main/common/components/*.o')
COMMON_OBJ += Glob('#/../bin/main/common/graph/*.o')  + Glob('#/../bin/main/common/random/*.o')
COMMON_OBJ += Glob('#/../bin/main/common/io/*.o') + Glob('#/../bin/main/common/components/socket/zmq_sockets/*.o')
COMMON_OBJ += Glob('#/../bin/main/common/util/config/*.o') + Glob('#/../bin/main/common/components/socket/isocket/*.o')
COMMON_OBJ += Glob('#/../bin/main/common/graph/builder/*.o')

SConscript([
	'main/algos/simrank_one_computer/SConscript',
    'main/algos/simrank_multithread/SConscript',			
    'main/algos/simrank_odd_even/SConscript',
    'main/algos/simrank_store_first/SConscript',
    'main/algos/simrank_update/SConscript',
    'main/algos/simple_mock_algo/SConscript',
    'main/algos/pagerank/SConscript',
    'main/algos/pagerank_non_block/SConscript',
    'main/algos/clever_pagerank/SConscript',
    'main/algos/custom_non_block/SConscript',
    'main/algos/custom_multi_nonblock/SConscript',
    'main/algos/counter_inverse/SConscript',
    'main/algos/counter_inverse_pagerank/SConscript',
    'main/algos/psimrank/SConscript',
    'main/algos/bitprop/SConscript',
    'main/algos/als/SConscript',
    'main/algos/als_multi/SConscript',
    'main/algos/als_multi_2step/SConscript'
     ],
    exports = ['env', 'COMMON_OBJ'])


ALGO_OBJ = Glob('#/../bin/main/algos/simrank_odd_even/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/simrank_store_first/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/simrank_update/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/pagerank/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/pagerank_non_block/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/clever_pagerank/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/psimrank/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/simple_mock_algo/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/bitprop/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/custom_non_block/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/custom_multi_nonblock/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/counter_inverse/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/counter_inverse_pagerank/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/als/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/als_multi/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/als_multi_2step/*.o')

SConscript([
    'main/dmoz/SConscript',
    'main/algos/algo_components/algo_base/SConscript',
    'main/algos/algo_components/master_base/SConscript',
    'main/algos/algo_components/factories/SConscript',
    'main/algos/algo_components/SConscript',
    'main/algos/algo_components/test_node_factories/SConscript'
	],
    exports = ['env', 'COMMON_OBJ', 'ALGO_OBJ'])

ALGO_OBJ += Glob('#/../bin/main/algos/algo_components/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/algo_components/test_node_factories/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/algo_components/algo_base/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/algo_components/master_base/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/algo_components/factories/*.o')

SConscript([
    'main/common/tools/SConscript'
	],
    exports = ['env', 'COMMON_OBJ', 'ALGO_OBJ'])

SConscript([
    'main/algos/task/SConscript'
	],
    exports = ['env', 'COMMON_OBJ', 'ALGO_OBJ'])

if testCompile: 
  SConscript([
    'test/common/SConscript',
    'test/common/graph_converter/SConscript',
    'test/algos/SConscript',
    'test/algos/als/SConscript',
    'test/algos/new_simple_mock_algo/SConscript',
    'test/algos/pagerank/SConscript',
    #'test/algos/simple_mock_algo/SConscript',
    #'test/algos/simrank_update/SConscript',
    #'test/algos/simrank_store_first/SConscript',
    #'test/algos/simrank_odd_even/SConscript',
    #'test/algos/psimrank/SConscript',
    #'test/algos/bitprop/SConscript',
    #'test/algos/counter_inverse/SConscript',
    #'test/algos/counter_inverse_pagerank/SConscript',
    'test/dmoz/SConscript',
    'test/useFileSystem/algos/SConscript',
    'test/useFileSystem/common/SConscript',
    'test/useFileSystem/common/socket/SConscript',
    'test/useFileSystem/common/edge_list_builder_tests/SConscript',
    'test/useFileSystem/common/edge_list_builder_tests_with_algo/SConscript',
    'test/useFileSystem/dmoz/SConscript',
    'test/shtest/SConscript',
    ],
    exports = ['env', 'COMMON_OBJ', 'ALGO_OBJ'])
