# -O3 jobban optimalizal
# -ggdb ezzel kell forditani, ha gdb-vel akarjuk debuggolni
# -pg gprof miatt?
# -g valgrind mint ?

# -O3 jobban optimalizal
# -ggdb ezzel kell forditani, ha gdb-vel akarjuk debuggolni
# -pg gprof miatt?
# -g valgrind mint ?

flags = ['-O3', '-g', '-ggdb', '-Wall']
#flags = [ '-g', '-ggdb', '-Wall']

GMOCK= "#../dep/gmock/"
LOG4CPP = "#../dep/log4cpp"

env = Environment(
        CXX = 'g++',
        CCFLAGS = flags,
        CPPPATH=[ '#.',
          GMOCK + '/include/',
	  '#../dep/log4cpp/include/'],
        LIBPATH=['/usr/local/googlecode/lib', '#../dep/gmp/lib/',
		'#../dep/log4cpp/lib/', GMOCK + 'build'] ,
        LIBS=['gflags', 'gtest', 'pthread', 'liblog4cpp', 'libgmock']
        #LIBS=['gflags', 'gtest', 'gmp', 'gmpxx', 'pthread', 'liblog4cpp']
)

SConscript([
    'main/common/SConscript',
    'main/dmoz/SConscript',
    'main/algos/simrank_one_computer/SConscript',	
    'main/algos/simrank_odd_even/SConscript',
    'main/algos/simrank_store_first/SConscript',
    'main/algos/simrank_update/SConscript', 
    'main/algos/SConscript',
#'test/common/SConscript',
#    'test/common/graph_converter/SConscript',
#    'test/algos/SConscript',
#    'test/algos/simple_mock_algo/SConscript',
#    'test/algos/simrank_update/SConscript',
#    'test/algos/simrank_store_first/SConscript',
#    'test/dmoz/SConscript',
#    'test/useFileSystem/common/SConscript',
#    'test/shtest/SConscript',
    ],
    exports = ['env'])
