# -O3 jobban optimalizal
# -ggdb ezzel kell forditani, ha gdb-vel akarjuk debuggolni
# -pg gprof miatt?
# -g valgrind mint ?

# -O3 jobban optimalizal
# -ggdb ezzel kell forditani, ha gdb-vel akarjuk debuggolni
# -pg gprof miatt?
# -g valgrind mint ?

flags = ['-O3', '-g', '-ggdb', '-Wall']
#flags = [ '-g', '-ggdb', '-Wall']

GMOCK= "#../dep/gmock/"
LOG4CPP = "#../dep/log4cpp"
GMP = "#../dep/gmp/"

env = Environment(
        CXX = 'g++',
        CCFLAGS = flags,
        CPPPATH=[ '#.',
          GMOCK + '/include/', '#../dep/log4cpp/include/', GMP + 'include/'],
        LIBPATH=['/usr/local/googlecode/lib', GMP + 'lib/',
		'#../dep/log4cpp/lib/', GMOCK + 'build'] ,
        LIBS=['gflags', 'gtest', 'pthread', 'liblog4cpp', 'libgmock', 'gmp', 'gmpxx']
        #LIBS=['gflags', 'gtest', 'gmp', 'gmpxx', 'pthread', 'liblog4cpp']
)

testCompile = ARGUMENTS.get('test', False)

"""
ALGO_OBJ = ['#/../bin/main/algos/algo.o', '#/../bin/main/algos/master.o', '#/../bin/main/algos/node.o', '#/../bin/main/algos/inner_master.o']

DESER_OBJ = Glob('#/../bin/main/algos/simrank_odd_even/*.o')
DESER_OBJ += Glob('#/../bin/main/algos/simrank_update/*.o')
DESER_OBJ += Glob('#/../bin/main/algos/simrank_store_first/*.o')
DESER_OBJ += Glob('#/../bin/main/algos/pagerank/*.o')
DESER_OBJ += ['#/../bin/main/algos/psimrank/psimrank_deserializer.o', '#/../bin/main/algos/psimrank/psimrank_node.o']
DESER_OBJ += ['#/../bin/test/algos/simple_mock_algo/simple_mock_deserializer.o', '#/../bin/test/algos/simple_mock_algo/simple_mock_node.o']"""

DESER_OBJ = ''
SConscript([
    'main/common/SConscript'],
    exports = ['env'])
    
COMMON_OBJ = Glob('#/../bin/main/common/components/socket/*.o') + Glob('#/../bin/main/common/util/*.o')
COMMON_OBJ += Glob('#/../bin/main/common/thread/*.o') + Glob('#/../bin/main/common/components/*.o')
COMMON_OBJ += Glob('#/../bin/main/common/graph/*.o')  + Glob('#/../bin/main/common/random/*.o')

SConscript([
	'main/algos/simrank_one_computer/SConscript',
    'main/algos/simrank_multithread/SConscript',			
    'main/algos/simrank_odd_even/SConscript',
    'main/algos/simrank_store_first/SConscript',
    'main/algos/simrank_update/SConscript',
    'main/algos/simple_mock_algo/SConscript',
    'main/algos/pagerank/SConscript',
    'main/algos/psimrank/SConscript',
     ],
    exports = ['env', 'COMMON_OBJ'])


ALGO_OBJ = Glob('#/../bin/main/algos/simrank_odd_even/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/simrank_store_first/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/simrank_update/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/pagerank/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/psimrank/*.o')
ALGO_OBJ += Glob('#/../bin/main/algos/simple_mock_algo/*.o')

#ALGO_OBJ += ['#/../bin/test/algos/simple_mock_algo/simple_mock_node.o', '#/../bin/test/algos/simple_mock_algo/simple_mock_deserializer.o', '#/../bin/test/algos/simple_mock_algo/simple_mock_inner_master.o']

SConscript([
    'main/dmoz/SConscript',
    'main/algos/SConscript',
	],
    exports = ['env', 'COMMON_OBJ', 'DESER_OBJ', 'ALGO_OBJ'])

ALGO_OBJ += ['#/../bin/main/algos/master.o', '#/../bin/main/algos/inner_master.o', 
'#/../bin/main/algos/node_factory.o', '#/../bin/main/algos/algo_builder.o', '#/../bin/main/algos/node.o',
'#/../bin/main/algos/algo.o','#/../bin/main/algos/node_factory_helper.o', '#/../bin/main/algos/test_simrank_odd_even_node_fatory.o',
'#/../bin/main/algos/cluster.o', '#/../bin/main/algos/test_master_builder.o', '#/../bin/main/algos/IMasterBuilder.o', '#/../bin/main/algos/inner_master_factory.o']

if testCompile: 
  SConscript([
    'test/common/SConscript',
    'test/common/graph_converter/SConscript',
    'test/algos/SConscript',
    'test/algos/simple_mock_algo/SConscript',
    'test/algos/simrank_update/SConscript',
    'test/algos/simrank_store_first/SConscript',
    'test/algos/simrank_odd_even/SConscript',
    'test/algos/psimrank/SConscript',
    'test/dmoz/SConscript',
    'test/useFileSystem/common/SConscript',
    'test/useFileSystem/common/socket/SConscript',
    'test/useFileSystem/common/edge_list_builder_tests/SConscript',
    'test/useFileSystem/common/edge_list_builder_tests_with_algo/SConscript',
    'test/useFileSystem/dmoz/SConscript',
    'test/shtest/SConscript',
    ],
    exports = ['env', 'COMMON_OBJ', 'DESER_OBJ', 'ALGO_OBJ'])
