Import('env', 'ALGO_OBJ', 'COMMON_OBJ')

env.Object(Glob('*.cpp'))

env.Program('crawl_edge_list_builder_with_simrank', ['crawl_edge_list_builder_with_simrank.cpp']  + COMMON_OBJ + ALGO_OBJ)
env.Program('filter_edge_list_builder_with_simrank', ['filter_edge_list_builder_with_simrank.cpp'] + COMMON_OBJ + ALGO_OBJ)
env.Program('edge_list_builder_with_simrank', ['edge_list_builder_with_simrank.cpp'] + COMMON_OBJ + ALGO_OBJ)