/*
 * mock_node.h
 *
 *  Created on: 2013.08.08.
 *      Author: kisstom
 */

#ifndef MOCK_SIMRANK_UPDATE_NODE_H_
#define MOCK_SIMRANK_UPDATE_NODE_H_

//#include "gmock/gmock.h"
#include "gmock/gmock.h"
#include "../../../main/algos/simrank_update/simrank_update_node.h"

// generated by:
// . ../../path_config.sh; "$GMOCK"/scripts/generator/gmock_gen.py test/gmock_example_maxfreq.h FrequencyCounter
//

class MockSimrankUpdateNode : public SimrankUpdateNode {
 public:
  MOCK_METHOD1(update, void(RandomWalk*));
  MOCK_METHOD0(beforeIteration, void());
  MOCK_METHOD0(afterIteration, bool());
  MOCK_METHOD0(sender, void());
  MOCK_METHOD1(initFromMaster, void(string));
  MOCK_METHOD2(initData, void(string, long));
  MOCK_METHOD1(setPartitionIndex, void(int));
};



#endif /* MOCK_NODE_H_ */
