function mylog(x) {
  if (x <= 0) return -50
  return log(x)
}

function logxpy(x, y) {
  return mylog(div(x, y))
}

function div(x, y) {
  if (x == 0 && y == 0) return 1
  if (x != 0 && y == 0) return 0
  return x/y 
}

function min(x, y) {
  if (x < y) return x
  else return y
}

function thr_min(x, y, z) {
  return min(min(x, y), z)
}

function max(x, y) {
  if (x > y) return x
  else return y
}

function thr_max(x, y, z) {
  return max(max(x, y), z)
}

function thr_avg(x, y, z) {
  return (x+y+z)/3
}

BEGIN{
  HOSTNAME = 1
  PAGERANK_MAXPRFEAT = 4
  PAGERANK_HOSTFEAT = 5
  AVGININ_MAXPRFEAT = 8
  AVGININ_HOSTFEAT = 9
  AVGINOUT_MAXPRFEAT = 12
  AVGINOUT_HOSTFEAT = 13
  AVGOUTOUT_MAXPRFEAT = 16
  AVGOUTOUT_HOSTFEAT = 17
  INDEGREE_MAXPRFEAT = 20
  INDEGREE_HOSTFEAT = 21
  OUTDEGREE_MAXPRFEAT = 24
  OUTDEGREE_HOSTFEAT = 25
  RECIPROC_MAXPRFEAT = 28
  RECIPROC_HOSTFEAT = 29
  SUPPORT_AT_DIST_2_MAXPRFEAT = 32
  SUPPORT_AT_DIST_2_HOSTFEAT = 33
  SUPPORT_AT_DIST_3_MAXPRFEAT = 36
  SUPPORT_AT_DIST_3_HOSTFEAT = 37
  SUPPORT_AT_DIST_4_MAXPRFEAT = 40
  SUPPORT_AT_DIST_4_HOSTFEAT = 41
  TRUNCATED1_MAXPRFEAT = 44
  TRUNCATED1_HOSTFEAT = 45
  TRUNCATED2_MAXPRFEAT = 48
  TRUNCATED2_HOSTFEAT = 49
  TRUNCATED3_MAXPRFEAT = 52
  TRUNCATED3_HOSTFEAT = 53
  TRUNCATED4_MAXPRFEAT = 56
  TRUNCATED4_HOSTFEAT = 57
  LABEL = 58

  AVGOUTIN_HOSTFEAT = 59
  AVGOUTIN_MAXPRFEAT = 60
  HP_EQ_MP = 61
  PRSIGMA_HOSTFEAT = 62
  PRSIGMA_MAXPRFEAT =63

  ORS = " "
}
{
  if (NR > 1)   printf "\n"
  print $HOSTNAME
  print mylog($INDEGREE_HOSTFEAT), mylog($INDEGREE_MAXPRFEAT), mylog($OUTDEGREE_HOSTFEAT), mylog($OUTDEGREE_MAXPRFEAT)
  print mylog($RECIPROC_HOSTFEAT), mylog($RECIPROC_MAXPRFEAT)

  ## assortativity szeru
  print logxpy($INDEGREE_HOSTFEAT, $AVGININ_HOSTFEAT), logxpy($INDEGREE_MAXPRFEAT, $AVGININ_MAXPRFEAT), logxpy($OUTDEGREE_HOSTFEAT, $AVGOUTOUT_HOSTFEAT), logxpy($OUTDEGREE_MAXPRFEAT, $AVGOUTOUT_MAXPRFEAT)

  print mylog($AVGINOUT_HOSTFEAT), mylog($AVGINOUT_MAXPRFEAT), mylog($AVGINOUT_HOSTFEAT * $OUTDEGREE_HOSTFEAT),  mylog($AVGINOUT_MAXPRFEAT * $OUTDEGREE_MAXPRFEAT)
  print mylog($AVGOUTIN_HOSTFEAT), mylog($AVGOUTIN_MAXPRFEAT), mylog($AVGOUTIN_HOSTFEAT * $INDEGREE_HOSTFEAT),  mylog($AVGOUTIN_MAXPRFEAT * $INDEGREE_MAXPRFEAT)

  # pr-es
  print $HP_EQ_MP, mylog($PAGERANK_HOSTFEAT), mylog($PAGERANK_MAXPRFEAT)
  print logxpy($INDEGREE_HOSTFEAT, $PAGERANK_HOSTFEAT), logxpy($INDEGREE_MAXPRFEAT, $PAGERANK_MAXPRFEAT), logxpy($OUTDEGREE_HOSTFEAT, $PAGERANK_HOSTFEAT), logxpy($OUTDEGREE_MAXPRFEAT, $PAGERANK_MAXPRFEAT)
  print mylog($PRSIGMA_HOSTFEAT), mylog($PRSIGMA_MAXPRFEAT), logxpy($PRSIGMA_HOSTFEAT, $PAGERANK_HOSTFEAT), logxpy($PRSIGMA_MAXPRFEAT, $PAGERANK_MAXPRFEAT)
  print div($PAGERANK_MAXPRFEAT, $PAGERANK_HOSTFEAT)
  
  # bitprop-os
  print mylog($INDEGREE_HOSTFEAT), mylog($SUPPORT_AT_DIST_2_HOSTFEAT), mylog($SUPPORT_AT_DIST_3_HOSTFEAT), mylog($SUPPORT_AT_DIST_4_HOSTFEAT), mylog($INDEGREE_MAXPRFEAT), mylog($SUPPORT_AT_DIST_2_MAXPRFEAT)
  print mylog($SUPPORT_AT_DIST_3_MAXPRFEAT), mylog($SUPPORT_AT_DIST_4_MAXPRFEAT)

  # bitprop per pr-es
  print logxpy($INDEGREE_HOSTFEAT, $PAGERANK_HOSTFEAT), logxpy($SUPPORT_AT_DIST_2_HOSTFEAT, $PAGERANK_HOSTFEAT)
  print logxpy($SUPPORT_AT_DIST_3_HOSTFEAT, $PAGERANK_HOSTFEAT), logxpy($SUPPORT_AT_DIST_4_HOSTFEAT, $PAGERANK_HOSTFEAT)
  print logxpy($INDEGREE_MAXPRFEAT, $PAGERANK_MAXPRFEAT), logxpy($SUPPORT_AT_DIST_2_MAXPRFEAT,$PAGERANK_MAXPRFEAT)
  print logxpy($SUPPORT_AT_DIST_3_MAXPRFEAT,$PAGERANK_MAXPRFEAT), logxpy($SUPPORT_AT_DIST_4_MAXPRFEAT,$PAGERANK_MAXPRFEAT)
  print logxpy($SUPPORT_AT_DIST_4_HOSTFEAT, $SUPPORT_AT_DIST_3_HOSTFEAT), logxpy($SUPPORT_AT_DIST_3_HOSTFEAT, $SUPPORT_AT_DIST_2_HOSTFEAT), logxpy($SUPPORT_AT_DIST_2_HOSTFEAT, $INDEGREE_HOSTFEAT)
  print , logxpy($SUPPORT_AT_DIST_3_MAXPRFEAT, $SUPPORT_AT_DIST_2_MAXPRFEAT), logxpy($SUPPORT_AT_DIST_2_MAXPRFEAT, $INDEGREE_MAXPRFEAT)
  
  print mylog(thr_min(div($SUPPORT_AT_DIST_4_HOSTFEAT,$SUPPORT_AT_DIST_3_HOSTFEAT), div($SUPPORT_AT_DIST_3_HOSTFEAT,$SUPPORT_AT_DIST_2_HOSTFEAT), div($SUPPORT_AT_DIST_2_HOSTFEAT,$INDEGREE_HOSTFEAT)))
  print mylog(thr_max(div($SUPPORT_AT_DIST_4_HOSTFEAT,$SUPPORT_AT_DIST_3_HOSTFEAT), div($SUPPORT_AT_DIST_3_HOSTFEAT,$SUPPORT_AT_DIST_2_HOSTFEAT), div($SUPPORT_AT_DIST_2_HOSTFEAT,$INDEGREE_HOSTFEAT)))
  print mylog(thr_avg(div($SUPPORT_AT_DIST_4_HOSTFEAT,$SUPPORT_AT_DIST_3_HOSTFEAT), div($SUPPORT_AT_DIST_3_HOSTFEAT,$SUPPORT_AT_DIST_2_HOSTFEAT), div($SUPPORT_AT_DIST_2_HOSTFEAT,$INDEGREE_HOSTFEAT)))
  print mylog(thr_min(div($SUPPORT_AT_DIST_4_MAXPRFEAT,$SUPPORT_AT_DIST_3_MAXPRFEAT), div($SUPPORT_AT_DIST_3_MAXPRFEAT,$SUPPORT_AT_DIST_2_MAXPRFEAT), div($SUPPORT_AT_DIST_2_MAXPRFEAT,$INDEGREE_MAXPRFEAT)))
  print mylog(thr_max(div($SUPPORT_AT_DIST_4_MAXPRFEAT,$SUPPORT_AT_DIST_3_MAXPRFEAT), div($SUPPORT_AT_DIST_3_MAXPRFEAT,$SUPPORT_AT_DIST_2_MAXPRFEAT), div($SUPPORT_AT_DIST_2_MAXPRFEAT,$INDEGREE_MAXPRFEAT)))
  print mylog(thr_avg(div($SUPPORT_AT_DIST_4_MAXPRFEAT,$SUPPORT_AT_DIST_3_MAXPRFEAT), div($SUPPORT_AT_DIST_3_MAXPRFEAT,$SUPPORT_AT_DIST_2_MAXPRFEAT), div($SUPPORT_AT_DIST_2_MAXPRFEAT,$INDEGREE_MAXPRFEAT)))
  
  print logxpy($SUPPORT_AT_DIST_4_HOSTFEAT -$SUPPORT_AT_DIST_3_HOSTFEAT, $PAGERANK_HOSTFEAT), logxpy($SUPPORT_AT_DIST_3_HOSTFEAT -$SUPPORT_AT_DIST_2_HOSTFEAT, $PAGERANK_HOSTFEAT)
  print logxpy($SUPPORT_AT_DIST_2_HOSTFEAT -$INDEGREE_HOSTFEAT, $PAGERANK_HOSTFEAT)
  print logxpy($SUPPORT_AT_DIST_4_MAXPRFEAT-$SUPPORT_AT_DIST_3_MAXPRFEAT, $PAGERANK_MAXPRFEAT), logxpy($SUPPORT_AT_DIST_3_MAXPRFEAT-$SUPPORT_AT_DIST_2_MAXPRFEAT, $PAGERANK_MAXPRFEAT)
  print logxpy($SUPPORT_AT_DIST_2_MAXPRFEAT-$INDEGREE_MAXPRFEAT, $PAGERANK_MAXPRFEAT)

  print div($SUPPORT_AT_DIST_4_HOSTFEAT, $SUPPORT_AT_DIST_4_MAXPRFEAT), div($SUPPORT_AT_DIST_3_HOSTFEAT, $SUPPORT_AT_DIST_3_MAXPRFEAT), div($SUPPORT_AT_DIST_2_HOSTFEAT, $SUPPORT_AT_DIST_2_MAXPRFEAT)
  print div($INDEGREE_HOSTFEAT, $INDEGREE_MAXPRFEAT)

  print mylog($TRUNCATED1_HOSTFEAT), mylog($TRUNCATED2_HOSTFEAT), mylog($TRUNCATED3_HOSTFEAT), mylog($TRUNCATED4_HOSTFEAT)
  print mylog($TRUNCATED1_MAXPRFEAT), mylog($TRUNCATED2_MAXPRFEAT), mylog($TRUNCATED3_MAXPRFEAT), mylog($TRUNCATED4_MAXPRFEAT)

  print logxpy($TRUNCATED1_HOSTFEAT, $PAGERANK_HOSTFEAT), logxpy($TRUNCATED2_HOSTFEAT, $PAGERANK_HOSTFEAT),logxpy($TRUNCATED3_HOSTFEAT, $PAGERANK_HOSTFEAT),logxpy($TRUNCATED4_HOSTFEAT, $PAGERANK_HOSTFEAT)
  print logxpy($TRUNCATED1_MAXPRFEAT, $PAGERANK_MAXPRFEAT), logxpy($TRUNCATED2_MAXPRFEAT, $PAGERANK_MAXPRFEAT), logxpy($TRUNCATED3_MAXPRFEAT, $PAGERANK_MAXPRFEAT)
  print logxpy($TRUNCATED4_MAXPRFEAT, $PAGERANK_MAXPRFEAT)

  print div($TRUNCATED4_HOSTFEAT, $TRUNCATED3_HOSTFEAT), div($TRUNCATED3_HOSTFEAT, $TRUNCATED2_HOSTFEAT), div($TRUNCATED2_HOSTFEAT, $TRUNCATED1_HOSTFEAT)
  print div($TRUNCATED4_MAXPRFEAT, $TRUNCATED3_MAXPRFEAT), div($TRUNCATED3_MAXPRFEAT, $TRUNCATED2_MAXPRFEAT), div($TRUNCATED2_MAXPRFEAT, $TRUNCATED1_MAXPRFEAT)

  print mylog(thr_min(div($TRUNCATED4_MAXPRFEAT, $TRUNCATED3_MAXPRFEAT), div($TRUNCATED3_MAXPRFEAT, $TRUNCATED2_MAXPRFEAT), div($TRUNCATED2_MAXPRFEAT, $TRUNCATED1_MAXPRFEAT)))
  print mylog(thr_max(div($TRUNCATED4_MAXPRFEAT, $TRUNCATED3_MAXPRFEAT), div($TRUNCATED3_MAXPRFEAT, $TRUNCATED2_MAXPRFEAT), div($TRUNCATED2_MAXPRFEAT, $TRUNCATED1_MAXPRFEAT)))
  print mylog(thr_avg(div($TRUNCATED4_MAXPRFEAT, $TRUNCATED3_MAXPRFEAT), div($TRUNCATED3_MAXPRFEAT, $TRUNCATED2_MAXPRFEAT), div($TRUNCATED2_MAXPRFEAT, $TRUNCATED1_MAXPRFEAT)))
  print mylog(thr_min(div($TRUNCATED4_HOSTFEAT, $TRUNCATED3_HOSTFEAT), div($TRUNCATED3_HOSTFEAT, $TRUNCATED2_HOSTFEAT), div($TRUNCATED2_HOSTFEAT, $TRUNCATED1_HOSTFEAT)))
  print mylog(thr_max(div($TRUNCATED4_HOSTFEAT, $TRUNCATED3_HOSTFEAT), div($TRUNCATED3_HOSTFEAT, $TRUNCATED2_HOSTFEAT), div($TRUNCATED2_HOSTFEAT, $TRUNCATED1_HOSTFEAT)))
  print mylog(thr_avg(div($TRUNCATED4_HOSTFEAT, $TRUNCATED3_HOSTFEAT), div($TRUNCATED3_HOSTFEAT, $TRUNCATED2_HOSTFEAT), div($TRUNCATED2_HOSTFEAT, $TRUNCATED1_HOSTFEAT)))

  print div($TRUNCATED4_MAXPRFEAT, $TRUNCATED4_HOSTFEAT), div($TRUNCATED3_MAXPRFEAT, $TRUNCATED3_HOSTFEAT), div($TRUNCATED2_MAXPRFEAT, $TRUNCATED2_HOSTFEAT), div($TRUNCATED1_MAXPRFEAT, $TRUNCATED1_HOSTFEAT)
  ## new
 
}
