Import('env', 'COMMON_OBJ', 'ALGO_OBJ')

env.Program('simrank_store_first_test', ['simrank_store_first_test.cpp'] + COMMON_OBJ + ALGO_OBJ)
env.Program('simrank_store_first_deserializer_test', ['simrank_store_first_deserializer_test.cpp'] + COMMON_OBJ + ALGO_OBJ)
