Import('env')

COMMON_OBJ = Glob('#/../bin/main/common/components/*.o') + Glob('#/../bin/main/common/util/*.o')
COMMON_OBJ += Glob('#/../bin/main/common/components/socket/*.o') + Glob('#/../bin/main/common/thread/*.o')
COMMON_OBJ += Glob('#/../bin/main/common/graph/*.o') + Glob('#/../bin/main/common/random/*.o')
COMMON_OBJ += ['#/../bin/main/algos/node.o', '#/../bin/main/algos/algo.o']

COMMON_OBJ += Glob('#/../bin/main/algos/simrank_odd_even/*.o')
COMMON_OBJ += Glob('#/../bin/main/algos/simrank_update/*.o')
COMMON_OBJ += Glob('#/../bin/main/algos/simrank_store_first/*.o')
COMMON_OBJ += Glob('#/../bin/main/algos/pagerank/*.o')

COMMON_OBJ += ['#/../bin/main/algos/psimrank/psimrank_deserializer.o', '#/../bin/main/algos/psimrank/psimrank_node.o']

env.Program('simrank_store_first_test', ['simrank_store_first_test.cpp'] + COMMON_OBJ)
env.Program('simrank_store_first_deserializer_test', ['simrank_store_first_deserializer_test.cpp'] + COMMON_OBJ)
