Import('env')

env.Object(Glob('*.cpp'))

COMMON_OBJ = Glob('#/../bin/main/common/components/socket/*.o') + Glob('#/../bin/main/common/util/*.o')
COMMON_OBJ += Glob('#/../bin/main/common/components/*.o') + Glob('#/../bin/main/common/thread/*.o')
COMMON_OBJ += Glob('#/../bin/main/common/random/*.o') + Glob('#/../bin/main/common/graph/*.o')

COMMON_OBJ += Glob('#/../bin/main/algos/simrank_odd_even/*.o')
COMMON_OBJ += Glob('#/../bin/main/algos/simrank_store_first/*.o')
COMMON_OBJ += Glob('#/../bin/main/algos/simrank_update/*.o')

#COMMON_OBJ += [, ']

env.Program('node_task', ['node_task.cpp', 'node_factory.o', 'algo_builder.o', 'node.o', 'algo.o','node_factory_helper.o', 'test_simrank_odd_even_node_fatory.o' ] + COMMON_OBJ)

env.Program('master_task', ['master_task.cpp','IMasterBuilder.o', 'test_master_builder.o', 'inner_master_factory.o', 'master_builder.o', 'master.o', 'node.o',  'algo.o'] + COMMON_OBJ)
