Import('env', 'COMMON_OBJ', 'ALGO_OBJ')

env.Object(Glob('*.cpp'))


env.Program('node_task', ['master.o', 'inner_master.o', 'node_task.cpp', 'node_factory.o', 'algo_builder.o', 'node.o', 'algo.o','node_factory_helper.o', 'test_simrank_odd_even_node_fatory.o' ] + COMMON_OBJ + ALGO_OBJ)
env.Program('master_task', ['inner_master.o', 'master_task.cpp','IMasterBuilder.o', 'test_master_builder.o', 'inner_master_factory.o', 'master_builder.o', 'master.o', 'node.o',  'algo.o'] + COMMON_OBJ + ALGO_OBJ)
