Import('env')

COMMON_OBJ = Glob('#/../bin/main/common/components/socket/*.o') + Glob('#/../bin/main/common/util/*.o')
COMMON_OBJ += Glob('#/../bin/main/common/thread/*.o') + Glob('#/../bin/main/common/components/*.o')
COMMON_OBJ += Glob('#/../bin/main/common/graph/*.o')  + Glob('#/../bin/main/common/random/*.o')

env.Object(Glob('*.cpp'))

SIMPLE_MOCK_OBJ = Glob('../../algos/simple_mock_algo/*.o')
DESER_OBJ = Glob('#/../bin/main/algos/simrank_odd_even/*.o')
DESER_OBJ += Glob('#/../bin/main/algos/simrank_update/*.o')
DESER_OBJ += Glob('#/../bin/main/algos/simrank_store_first/*.o')
DESER_OBJ += Glob('#/../bin/main/algos/pagerank/*.o')

env.Program('test_simple_mock', ['../../../main/algos/algo.o', '../../../main/algos/master.o', '../../../main/algos/node.o'] + COMMON_OBJ + SIMPLE_MOCK_OBJ + DESER_OBJ)
