Import('env', 'COMMON_OBJ', 'ALGO_OBJ')

env.Program('simrank_odd_even_test', ['simrank_odd_even_test.cpp']  + COMMON_OBJ + ALGO_OBJ)
env.Program('simrank_test_small', ['simrank_test_small.cpp'] + COMMON_OBJ + ALGO_OBJ)