Import('env')

COMMON_OBJ = Glob('#/../bin/main/common/graph/*.o') + Glob('#/../bin/main/common/util/*.o')

env.Object(Glob('*.cpp'))
env.Program('sorted_vector_node_matrix_test', ['sorted_vector_node_matrix_test.cpp'] + COMMON_OBJ)
env.Program('edge_list_builder_test', ['edge_list_builder_test.cpp'] + COMMON_OBJ)
env.Program('test_sorted_vector_reader', ['test_sorted_vector_reader.cpp'] + COMMON_OBJ)
env.Program('file_util_test', ['file_util_test.cpp'] + COMMON_OBJ)
env.Program('edge_list_builder_tool', ['edge_list_builder_tool.cpp', '../../../main/common/graph/edgelist_container.o',
'../../../main/common/graph/edge_list_builder.o', '../../../main/common/util/util.o', '../../../main/common/util/logger_factory.o'])

NODE_OJBJECT = ['../../../main/algos/simrank_odd_even/simrank_odd_even_node.o', '../../../main/algos/node.o', '../../../main/algos/algo.o',
'../../../main/algos/simrank_odd_even/simrank_odd_even_deserializer.o']

COMPONENTS = Glob('#/../bin/main/common/thread/*.o') + Glob('#/../bin/main/common/components/*.o') + Glob('#/../bin/main/common/random/*.o') + Glob('#/../bin/main/common/components/socket/*.o')
COMPONENTS += Glob('#/../bin/main/algos/simrank_store_first/*.o') + Glob('#/../bin/main/algos/simrank_update/*.o')

env.Program('crawl_edge_list_builder_with_simrank', ['crawl_edge_list_builder_with_simrank.cpp', ] + COMMON_OBJ + NODE_OJBJECT + COMPONENTS)
