Import('env')

env.Object(Glob('*.cpp'))

env.Program('test_distanc_calculator', ['test_distanc_calculator.cpp', '../../main/dmoz/dmoz_reader.o'])
env.Program('fileter_trusted_url', ['fileter_trusted_url.cpp'])
env.Program('test_ndcg', ['test_ndcg.cpp', '../../main/dmoz/ndcg.o'])
env.Program('test_simrank_score', ['test_simrank_score.cpp', '../../main/dmoz/simrank.o'])
